### PR TITLE
WIP: Search Dark Theme

### PR DESCRIPTION
**Pull request by samstorment**
## Currently

Goal is to get a decent looking dark theme going with as minimally invasive changes as possible. I converted a lot of SCSS variables to CSS custom properties and added a `@media (prefers-color-scheme: dark)` to override those custom properties with different value for dark mode.

I pretty much just chose a bunch of different grays that look OK together. Things do still feel a fair bit off though. Here's some current issues:

* Some of the contrast is pretty bad 
* Many colors are still hard coded
* Naming is hard. Some examples:
    * `--clr-border-dim` vs `--clr-border-dark` are bad names. They both mean basically the same thing to me
    * You'd think `--clr-border-dark` would be used would be used only on borders, but the header box shadow uses it. The names are probably too specific

I'm thinking about trying to constrain the number of colors (like settling on one border color, one shadow color, etc.) to make the naming and future theming more straightforward while hopefully retaining the basic look of the site.

### CODE REVIEW

**Comment by vlofgren** [comment]
Looks like good progress!  

If you're looking for inspiration, the old dark design used to have some dashes of blue to make it possible to clearly distinguish elements without sacrificing contrast.  

https://web.archive.org/web/20231102011611/https://search.marginalia.nu/

image


You're definitely free to take this in a different direction and this in no way needs to be a re-creation of the old dark mode though.

**Comment by samstorment** [comment]
I've got the dark theme colors looking quite a bit nicer than my previous commit. Some more things I'm aware of that I haven't been able to test with dark theme are:

* The section of card search results when you search "browse:random"
* The `/site/{siteName}` page when you click the info link. It's got some mocked data but not the similar and linking domains sections

I'd guess things would look good on those pages but I'm not sure. Let me know if mocking things out is getting to be a headache and I can do some more digging into properly running things locally myself

**Comment by vlofgren** [comment]
I've patched the paperdoll to mock the requested data, https://github.com/MarginaliaSearch/MarginaliaSearch/commit/d227a09fb174f06fc79dc42cde891025baac2f84

**Comment by samstorment** [comment]
Well, I've made a mistake using `git rebase` trying to catch my branch back up with master and now my PR includes all of your commits. Since my changes are all in a single file, I'm going to treat this as a learning experience and try to fix it while preserving the correct git history. If I somehow manage to break things beyond repair, I guess I'll just make a new PR

**Comment by vlofgren** [comment]
Yeah we can always just do a squash merge if the history ends up a bit wonky on this branch. 

Though the main branch has its fair amount of git gore already, and IMO a super clean git histories matters much more when there's a larger number of contributors pushing changes left and right than when there's just a few people and there aren't many merge conflicts to deal with.

**Comment by samstorment** [comment]
I've got the dark theme to a point I'm fairly satisfied with so I suppose the PR is ready for a review.

**Comment by vlofgren** [comment]
I'm getting some poor contrast in a few locations using Chromium, specifically the hyperlinks in the footer have really poor contrast:

image

Also in the search form, the contrast is black on (almost) black for me  

image

In case you can't replicate, the problem goes away for me when I stick
```css
  input { color: #fff; }
  a { color: #fff; }
```
in the `@media (prefers-color-scheme: dark) {` block

**Comment by samstorment** [comment]
Weird! The color of the links and the form fields might be set to a default value determined by the OS, because I was not able to reproduce. 

For the inputs, I just globally gave form fields `color: inherit` so their color will just take the same color as the `body` element, which is how things already looked in all current cases I know of.

For the links, the best I could come up with is manually setting link colors so they look the same on all browsers all the time. I don't love this solution, but I don't really see a way around it.

I tried styling the links _only_ in `@media (prefers-color-scheme: dark)`, but there's an edge case that makes it not worth it to me. When you set an explicit color on `a`, that color gets inherited by `a:visited`. But because we need to set explicit colors on both `a` and `a:visited` for dark mode (because the browser defaults look bad for both), we can no longer rely on `a:visited` inheriting its color from `a`. I didn't want to introduce two subtly different styling "modes" for links based on dark vs light mode, so I decided to just set explicit styles all the time regardless of color theme.

The colors I went with are the Firefox link colors in both light and dark mode because I thought they looked fine.

Here's an example gif showing how `a:visited` inherits color. In light mode both links are just pink since `a` is styled but `a:visited` is not. In dark mode both states have explicit styles, so that inheritance is lost.

default-vs-explicit

**Comment by vlofgren** [comment]
Cool.  I poked around a bit and I think there's some tweaks to the colors that can be done to make the metaphor a bit more visually consistent.  Will get back to you with a suggestion, mostly AFK for a few days sorry about the delay.

**Comment by vlofgren** [comment]
I still think something is a bit off about the colors and I might go in and poke at it later to see if I can figure out what's bothering me, but whatever it is it's really minor and I don't want to leave this PR in limbo forever over an insubstantial hunch.  I've approved and will merge.  

Thanks

**Comment by samstorment** [comment]
No worries! I agree it could use some tweaking but at least now it's in a very tweak-able state. I could work on adding a JavaScript powered theme toggle so people who've set dark mode at the OS level can still use the light theme if they're not quite happy with the dark theme. Let me know if that's something you're interested in adding.

**Comment by vlofgren** [comment]
Yeah that would be great!

**Pull request merged**
